#!/bin/bash
set -e 



gnuplot -persist << EOF
#A

	set term x11 0
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'Solvent' at screen 0.45,0.005
     	#set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
	set style data histograms
	set style fill solid
	set key t r 
        set yrange [0:0.8]
	set ylabel "A-Hlcy" 
	set y2range [0:9]
	set y2tics border
	set y2label "RDF"
	set xtic rotate by -30
        set label 3 'Alpha Helicity and RDF Max of SRE A' at screen 0.23,0.98
	set xrange [-0.2:5]
	
        set title "253K"
	plot "alpha_rdfmax_mon_sreA_253" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
	"" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "294K"
        plot "alpha_rdfmax_mon_sreA_294" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "310K"
        plot "alpha_rdfmax_mon_sreA_310" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "350K"
        plot "alpha_rdfmax_mon_sreA_350" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"
	
	unset multiplot

#B

        set term x11 1

        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'Solvent' at screen 0.45,0.005
        #set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
        set style data histograms
        set style fill solid
        set key t r 
        set yrange [0:0.8]
        set ylabel "A-Hlcy" 
        set y2range [0:9]
        set y2tics border
        set y2label "RDF"
        set xtic rotate by -30
        set label 3 'Alpha Helicity and RDF Max of SRE B' at screen 0.23,0.98
        set xrange [-0.2:5]
        
        set title "253K"
        plot "alpha_rdfmax_mon_sreB_253" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "294K"
        plot "alpha_rdfmax_mon_sreB_294" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "310K"
        plot "alpha_rdfmax_mon_sreB_310" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"

        set title "350K"
        plot "alpha_rdfmax_mon_sreB_350" using 3:xtic(2) title "Alpha Helicity" lt rgb "#406090" ,\
        "" using 4 title "RDF Max" axes x1y2 lt rgb "#40FF00"


	pause -1

EOF


#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

