#!/bin/bash
set -e 

#used 1us for wat and 500ns for IL



#wat_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/secstruct_1us/all.dat > alpha+310hel_wat253.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/secstruct_1us/all.dat > alpha+310hel_wat294.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/secstruct_1us/all.dat > alpha+310hel_wat310.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/secstruct_1us/all.dat > alpha+310hel_wat350.dat

#CAGE_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_CAGE253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_CAGE294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_CAGE310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_CAGE350_1M.dat

#AAGE_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_AAGE253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_AAGE294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_AAGE310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_AAGE350_1M.dat

#EMIM_TFN_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_et253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_et294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_et310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_et350_1M.dat

#EMIM_Cl_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_ec253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_ec294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_ec310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_ec350_1M.dat

#K_TFN_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_kt253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_kt294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_kt310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_kt350_1M.dat

#K_Cl_1M_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_kc253_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_kc294_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_kc310_1M.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_kc350_1M.dat

#CAGE_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_CAGE253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_CAGE294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_CAGE310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_CAGE350_0.0XM.dat

#AAGE_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_AAGE253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_AAGE294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_AAGE310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_AAGE350_0.0XM.dat

#EMIM_TFN_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_et253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_et294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_et310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_et350_0.0XM.dat

#EMIM_Cl_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_ec253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_ec294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_ec310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_ec350_0.0XM.dat

#K_TFN_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_kt253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_kt294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_kt310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_kt350_0.0XM.dat

#K_Cl_0.0XM_sum
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/all.dat > alpha+310hel_kc253_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/all.dat > alpha+310hel_kc294_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/all.dat > alpha+310hel_kc310_0.0XM.dat
awk 'NR>1 {print $2+$6}' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/all.dat > alpha+310hel_kc350_0.0XM.dat




#wat_totalhel
#./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_wat.dat
#./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_wat.dat 
#./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_wat.dat
#./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_wat.dat

#CAGE_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_CAGE_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE253_0.0XM.dat >> totalhelavg_CAGE_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE253_1M.dat >> totalhelavg_CAGE_253.dat
#CAGE_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_CAGE_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE294_0.0XM.dat >> totalhelavg_CAGE_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE294_1M.dat >> totalhelavg_CAGE_294.dat
#CAGE_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_CAGE_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE310_0.0XM.dat >> totalhelavg_CAGE_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE310_1M.dat >> totalhelavg_CAGE_310.dat
#CAGE_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_CAGE_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE350_0.0XM.dat >> totalhelavg_CAGE_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_CAGE350_1M.dat >> totalhelavg_CAGE_350.dat


#AAGE_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_AAGE_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE253_0.0XM.dat >> totalhelavg_AAGE_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE253_1M.dat >> totalhelavg_AAGE_253.dat
#AAGE_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_AAGE_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE294_0.0XM.dat >> totalhelavg_AAGE_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE294_1M.dat >> totalhelavg_AAGE_294.dat
#AAGE_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_AAGE_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE310_0.0XM.dat >> totalhelavg_AAGE_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE310_1M.dat >> totalhelavg_AAGE_310.dat
#AAGE_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_AAGE_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE350_0.0XM.dat >> totalhelavg_AAGE_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_AAGE350_1M.dat >> totalhelavg_AAGE_350.dat


#EMIM_TFN_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_et_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et253_0.0XM.dat >> totalhelavg_et_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et253_1M.dat >> totalhelavg_et_253.dat
#EMIM_TFN_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_et_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et294_0.0XM.dat >> totalhelavg_et_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et294_1M.dat >> totalhelavg_et_294.dat
#EMIM_TFN_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_et_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et310_0.0XM.dat >> totalhelavg_et_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et310_1M.dat >> totalhelavg_et_310.dat
#EMIM_TFN_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_et_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et350_0.0XM.dat >> totalhelavg_et_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_et350_1M.dat >> totalhelavg_et_350.dat


#EMIM_Cl_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_ec_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec253_0.0XM.dat >> totalhelavg_ec_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec253_1M.dat >> totalhelavg_ec_253.dat
#EMIM_Cl_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_ec_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec294_0.0XM.dat >> totalhelavg_ec_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec294_1M.dat >> totalhelavg_ec_294.dat
#EMIM_Cl_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_ec_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec310_0.0XM.dat >> totalhelavg_ec_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec310_1M.dat >> totalhelavg_ec_310.dat
#EMIM_Cl_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_ec_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec350_0.0XM.dat >> totalhelavg_ec_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_ec350_1M.dat >> totalhelavg_ec_350.dat


#K_TFN_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_kt_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt253_0.0XM.dat >> totalhelavg_kt_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt253_1M.dat >> totalhelavg_kt_253.dat
#K_TFN_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_kt_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt294_0.0XM.dat >> totalhelavg_kt_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt294_1M.dat >> totalhelavg_kt_294.dat
#K_TFN_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_kt_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt310_0.0XM.dat >> totalhelavg_kt_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt310_1M.dat >> totalhelavg_kt_310.dat
#K_TFN_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_kt_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt350_0.0XM.dat >> totalhelavg_kt_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kt350_1M.dat >> totalhelavg_kt_350.dat


#K_Cl_totalhel_253
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat253.dat >> totalhelavg_kc_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc253_0.0XM.dat >> totalhelavg_kc_253.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc253_1M.dat >> totalhelavg_kc_253.dat
#K_Cl_totalhel_294
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat294.dat >> totalhelavg_kc_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc294_0.0XM.dat >> totalhelavg_kc_294.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc294_1M.dat >> totalhelavg_kc_294.dat
#K_Cl_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat310.dat >> totalhelavg_kc_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc310_0.0XM.dat >> totalhelavg_kc_310.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc310_1M.dat >> totalhelavg_kc_310.dat
#K_Cl_totalhel_310
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_wat350.dat >> totalhelavg_kc_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc350_0.0XM.dat >> totalhelavg_kc_350.dat
./../../../analysis_scripts/avg_sterror 1 alpha+310hel_kc350_1M.dat >> totalhelavg_kc_350.dat



gnuplot -persist << EOF
	
#CAGE
	set term x11 0
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of CAGE (M)' 
        set ylabel 'Fraction of Total-Helicity' 
	set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs CAGE Concentration' 
	set xrange [-0.01:1.013]
	conc = "0 0.072 1.003"
	set bars 4
plot "totalhelavg_CAGE_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_CAGE_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_CAGE_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_CAGE_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle

#AAGE
        set term x11 1
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of mCAGE (M)' 
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs mCAGE Concentration' 
        set xrange [-0.01:1.012]
        conc = "0 0.085 1.002"
        set bars 4
plot "totalhelavg_AAGE_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_AAGE_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_AAGE_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_AAGE_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle

#EMIM_TFN
        set term x11 2  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of EMIM_TFN (M)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs EMIM_TFN Concentration' 
        set xrange [-0.01:1.015]
        conc = "0 0.090 1.005"
        set bars 4
plot "totalhelavg_et_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_et_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_et_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_et_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle

#EMIM_Cl
        set term x11 3
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of EMIM_Cl (M)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs EMIM_Cl Concentration'
        set xrange [-0.01:1.011]
        conc = "0 0.095 1.001"
        set bars 4
plot "totalhelavg_ec_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_ec_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_ec_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_ec_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle

#K_TFN
        set term x11 4
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of K_TFN (M)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs K_TFN Concentration' 
        set xrange [-0.01:1.016]
        conc = "0 0.094 1.006"
        set bars 4
plot "totalhelavg_kt_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_kt_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_kt_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_kt_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle

#K_Cl
        set term x11 5
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Concentration of Sets of K_Cl (M)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:1]
        set title 'Total Helicity vs K_Cl Concentration' 
        set xrange [-0.01:1.011]
        conc = "0 0.099 1.001"
        set bars 4
plot "totalhelavg_kc_253.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "253" linestyle 1, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"totalhelavg_kc_294.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "294" linestyle 2, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"totalhelavg_kc_310.dat"  using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "310" linestyle 3, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle,\
"totalhelavg_kc_350.dat"   using (word(conc,int(column(0))+1)+0.0):1 with linespoints title "350" linestyle 4, "" using (word(conc,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 4 notitle


	pause -1

EOF

rm totalhelavg_*.dat
rm alpha+310hel_*.dat
