#!/bin/bash
set -e 

#6th column is 3-10

cat /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_A.dat >> watss_alltempsA.dat
cat /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_B.dat >> watss_alltempsB.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_A.dat >> cagess_alltempsA.dat
cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_B.dat >> cagess_alltempsB.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_A.dat >> cagess_alltemps_lcA.dat
cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/*K/converged_analysis/sre_analysis/alpha_helicity/avg_B.dat >> cagess_alltemps_lcB.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> aagess_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> etss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> ecss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> ktss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> kcss_alltemps.dat



gnuplot -persist << EOF
	
#Alpha
	set term x11 0
	set multiplot layout 2,1  rowsfirst
	set tmargin 2
	set bmargin 5	

        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Alpha-Helicity'  
	set key b r
        #set yrange [0:0.9]
        set title 'Alpha Helicity of SRE-A' 
	set xrange [252:351]
	#set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
	temperature = "253 294 310 350"	
plot "watss_alltempsA.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "Water",\
"cagess_alltempsA.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (HC)",\
"cagess_alltemps_lcA.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (LC)"

        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title 'Alpha Helicity of SRE-B' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
plot "watss_alltempsB.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "Water",\
"cagess_alltempsB.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (HC)",\
"cagess_alltemps_lcB.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (LC)"


	pause -1

EOF

rm *ss_alltempsA.dat
rm *ss_alltempsB.dat
rm *ss_alltemps_lcA.dat
rm *ss_alltemps_lcB.dat
#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

