#!/bin/bash
set -e 
#/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis

gnuplot -persist << EOF 
	
#Alpha
	set term x11 1	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (ns)'
        set ylabel 'Fraction of Alpha-Helicity'  
	set key b r
        set yrange [0:1]
        set title 'Alpha Helicity of Monomer vs Temperature in 1 M mCAGE' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):2 every 1500 w l title "350 K" linecolor rgb "black",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):2 every 1500 w l title "310 K" linecolor rgb "red",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):2 every 1500 w l title "294 K" linecolor rgb "orange",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):2 every 1500 w l title "253 K" linecolor rgb "cyan"


#Total Helicity
        set term x11 2  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (ns)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        set yrange [0:1]
	set title 'Total Helicity of Monomer vs Temperature in 1 M mCAGE' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):(column(2)+column(6)) every 1500 w l title "350 K" linecolor rgb "black" ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):(column(2)+column(6)) every 1500 w l title "310 K" linecolor rgb "red",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):(column(2)+column(6)) every 1500 w l title "294 K" linecolor rgb "orange" ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/all.dat" using (0.002 * column(1)):(column(2)+column(6)) every 1500 w l title "253 K" linecolor rgb "cyan" 

	pause -1

EOF

