#!/bin/bash
set -e 

#6th column is 3-10

cat /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis/analysis_1us/avg_all.dat >> watss_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/*K/converged_analysis/analysis_1us/avg_all.dat >> cagess_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/*K/converged_analysis/secstruct_1us/avg_all.dat >> cagess_alltemps_lc.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> aagess_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> etss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> ecss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> ktss_alltemps.dat

#cat /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/*K/converged_analysis/avg_all.dat >> kcss_alltemps.dat



gnuplot -persist << EOF
	
#Alpha
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Alpha-Helicity'  
	set key b r
        #set yrange [0:0.9]
        set title 'Alpha Helicity of Monomer' 
	set xrange [252:351]
	#set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
	temperature = "253 294 310 350"	
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (HC)",\
"cagess_alltemps_lc.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE (LC)"
#"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "mCAGE",\
#"etss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "EMIM_TFN",\
#"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "EMIM_Cl",\
#"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "K_TFN",\
#"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2  title "K_Cl"

#None
        set term x11 1  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of No Secondary Structure'  
        set key b r
        #set yrange [0:0.9]
        set title 'Fraction of No Secondary Structure of Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
        
	plot "watss_alltemps.dat" using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "Water",\
	"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "CAGE (LC)"
	#"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "mCAGE",\
	#"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "EMIM_TFN",\
	#"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "EMIM_Cl",\
	#"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "K_TFN",\
	#"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):3 with linespoints ps 2 title "K_Cl" 

#Para
        set term x11 2  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Parallel Beta Sheets'  
        set key b r
        #set yrange [0:0.9]
        set title 'Fraction of Parallel Beta Sheets of Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
        plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "CAGE (HC)",\
"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "CAGE (LC)"
#"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "mCAGE",\
#"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "EMIM_TFN",\
#"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "EMIM_Cl",\
#"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "K_TFN",\
#"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):4 with linespoints ps 2 title "K_Cl" 

#Anti
        set term x11 3  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Anti-Parallel Beta Sheets'  
        set key b r
        #set yrange [0:0.9]
        set title 'Fraction of Anti-Parallel Beta Sheets of Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
	plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "Water",\
	"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "CAGE (LC)"
	#"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "mCAGE",\
	#"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "EMIM_TFN",\
	#"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "EMIM_Cl",\
	#"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "K_TFN",\
	#"kcss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):5 with linespoints ps 2 title "K_Cl" 


#3-10
        set term x11 4  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of 3-10 Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title '3-10 Helicity of Monomer'
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
	plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "Water",\
       	"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2   title "CAGE (LC)"
        #"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "mCAGE",\
        #"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "EMIM_TFN",\
        #"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "EMIM_Cl",\
        #"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "K_TFN",\
        #"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "K_Cl" 

#Pi
        set term x11 5  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Pi Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title 'Pi Helicity of Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350"         
	plot "watss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "Water",\
        "cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"  using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "CAGE (LC)"
        #"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "mCAGE",\
        #"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "EMIM_TFN",\
        #"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "EMIM_Cl",\
        #"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "K_TFN",\
        #"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):7 with linespoints ps 2  title "K_Cl" 

#Turn
        set term x11 6  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Turns Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title 'Turns of Monomer'
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2  title "Water",\
        "cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "CAGE (LC)"
        #"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "mCAGE",\
        #"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "EMIM_TFN",\
        #"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "EMIM_Cl",\
        #"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "K_TFN",\
        #"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):8 with linespoints ps 2 title "K_Cl" 


#Bend
        set term x11 7  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Bends'  
        set key b r
        #set yrange [0:0.9]
        set title 'Bends of Monomer (HC)' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350"         
	plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2  title "Water",\
        "cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "CAGE (HC)",\
	"cagess_alltemps_lc.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "CAGE (LC)"
        #"aagess_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "mCAGE",\
        #"etss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "EMIM_TFN",\
        #"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "EMIM_Cl",\
        #"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "K_TFN",\
        #"kcss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):9 with linespoints ps 2 title "K_Cl" 

#Total helicity
        set term x11 8  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Total Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title 'Total Helicity of Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "CAGE (HC)",\
"cagess_alltemps_lc.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "CAGE (LC)"
#"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "mCAGE",\
#"etss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "EMIM_TFN",\
#"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "EMIM_Cl",\
#"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "K_TFN",\
#"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2  title "K_Cl" 


	pause -1

EOF

rm *ss_alltemps.dat
rm *ss_alltemps_lc.dat
#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

