#!/bin/bash
set -e 


#using 1M (high) conc for ILs
#wat_rog.c0
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/radgyr.c0.out >> rogavg_wat.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c0.dat

#wat_rog.c1
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/radgyr.c1.out >> rogavg_wat.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.c1.dat

#CAGE_rog
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat

#mCAGE_rog
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_AAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_AAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_AAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_AAGE.dat

#wat_B26Ca-B12Ca.c0
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_B26Ca-B12Ca.c0 >> distavg_wat_B26Ca-B12Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c0.dat

#wat_B26Ca-B12Ca.c1
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_B26Ca-B12Ca.c1 >> distavg_wat_B26Ca-B12Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.c1.dat

#CAGE_B26Ca-B12Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat

#mCAGE_B26Ca-B12Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_AAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_AAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_AAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_AAGE_B26Ca-B12Ca.dat

#wat_B28Ca-B8Ca.c0
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_B28Ca-B8Ca.c0 >> distavg_wat_B28Ca-B8Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c0.dat

#wat_B28Ca-B8Ca.c1
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_B28Ca-B8Ca.c1 >> distavg_wat_B28Ca-B8Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.c1.dat

#CAGE_B28Ca-B8Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat

#mCAGE_B28Ca-B8Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_AAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_AAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_AAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_AAGE_B28Ca-B8Ca.dat

#wat_A19O-B25H.c0
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_A19O-B25H.c0 >> distavg_wat_A19O-B25H.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c0.dat

#wat_A19O-B25H.c1
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_A19O-B25H.c1 >> distavg_wat_A19O-B25H.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.c1.dat

#CAGE_A19O-B25H
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat

#mCAGE_A19O-B25H
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_AAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_AAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_AAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_AAGE_A19O-B25H.dat

#wat_A21neg-B22pos.c0
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_A21neg-B22pos.c0 >> distavg_wat_A21neg-B22pos.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c0.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c0.dat

#wat_A21neg-B22pos.c1
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/pop_clustering/dist_A21neg-B22pos.c1 >> distavg_wat_A21neg-B22pos.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c1.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.c1.dat

#CAGE_A21neg-B22pos
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat

#mCAGE_A21neg-B22pos
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_AAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_AAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_AAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_AAGE_A21neg-B22pos.dat

gnuplot -persist << EOF
	
#rog
	set term x11 1 font "arial, 14" 
	set key spacing 1.1
	
	set xlabel 'Temperature (K)'
        set ylabel 'Radius of Gyration (angstroms)'  
	set key t l 
        #set yrange [0:1]
	set xrange [252:351]
	temperature = "253 294 310 350"
	set bars 2
	set pointsize 1

	plot \
"rogavg_AAGE.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#009E73" title "In CAGE", "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 1 linecolor rgb "#009E73" notitle,\
"rogavg_CAGE.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#D55E00" title "In mCAGE", "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 1 linecolor rgb "#D55E00" notitle,\
"rogavg_wat.c1.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water", "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 1 linecolor rgb "#0072B2" notitle,\
"rogavg_wat.c0.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#0072B2" notitle, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 1 linecolor rgb "#0072B2" notitle

#distances
	set term x11 2 font "arial, 14"
        set multiplot layout 2,2 rows
        set tmargin 0.5
        set bmargin 4
        set lmargin 8
        set rmargin 2 
        set pointsize 1
        
#B26Ca-B12Ca
        #set yrange [0:0.9]
        set ylabel 'B26(Ca)-B12(Ca) (ang.)' 
        set xrange [250:353]
        temperature = "253 294 310 350"
        set bars 4
        set nokey
plot \
"distavg_CAGE_B26Ca-B12Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#009E73" title "In CAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#009E73" notitle,\
"distavg_AAGE_B26Ca-B12Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#D55E00" title "In mCAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#D55E00" notitle,\
"distavg_wat_B26Ca-B12Ca.c0.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle,\
"distavg_wat_B26Ca-B12Ca.c1.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle

#B28Ca-B8Ca
        #set yrange [0:0.9]
        set ylabel 'B28(Ca)-B8(Ca) (ang.)' 
        set xrange [250:353]
        temperature = "253 294 310 350"
        set bars 4
        set nokey
	plot \
"distavg_CAGE_B28Ca-B8Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#009E73" title "In CAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#009E73" notitle,\
"distavg_AAGE_B28Ca-B8Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#D55E00" title "In mCAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#D55E00" notitle,\
"distavg_wat_B28Ca-B8Ca.c0.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle,\
"distavg_wat_B28Ca-B8Ca.c1.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle

#A19O-B25H
        set xlabel 'Temperature (K)'
        #set yrange [0:0.9]
        set ylabel 'A19(O)-B25(H) (ang.)' 
        set xrange [250:353]
        temperature = "253 294 310 350"
        set bars 4
        set nokey
	plot \
"distavg_CAGE_A19O-B25H.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#009E73" title "In CAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#009E73" notitle,\
"distavg_AAGE_A19O-B25H.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#D55E00" title "In mCAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#D55E00" notitle,\
"distavg_wat_A19O-B25H.c0.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle,\
"distavg_wat_A19O-B25H.c1.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle

#A21neg-B22pos
        set xlabel 'Temperature (K)'
        #set yrange [0:0.9]
        set ylabel 'A21(Term. Os)-B22(Pos. Ns) (ang.)' 
        set xrange [250:353]
        temperature = "253 294 310 350"
        set bars 4
        set nokey
	plot \
"distavg_CAGE_A21neg-B22pos.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#009E73" title "In CAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#009E73" notitle,\
"distavg_AAGE_A21neg-B22pos.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints pt 7 lw 2 linecolor rgb "#D55E00" title "In mCAGE" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#D55E00" notitle,\
"distavg_wat_A21neg-B22pos.c0.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle,\
"distavg_wat_A21neg-B22pos.c1.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints pt 7 lw 2 linecolor rgb "#0072B2" title "In Water" , "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars pt 7 lw 2 linecolor rgb "#0072B2" notitle



	pause -1

EOF

rm rogavg_*.dat
rm distavg_*_B26Ca-B12Ca.c*.dat
rm distavg_*_B28Ca-B8Ca.c*.dat
rm distavg_*_A19O-B25H.c*.dat
rm distavg_*_A21neg-B22pos.c*.dat
rm distavg_*_B26Ca-B12Ca.dat
rm distavg_*_B28Ca-B8Ca.dat
rm distavg_*_A19O-B25H.dat
rm distavg_*_A21neg-B22pos.dat

#gv plot_ssalpha_wat.CAGE.AAGE_over_temp_1M_pops_handled.eps
#epstopdf ssalpha_wat.CAGE.AAGE_over_temp_1M_pops_handled.eps


