#!/bin/bash
set -e 

#using 1M (high) conc for ILs
#used 1us for wat and 500ns for IL

#wat_B26Ca-B12Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_wat_B26Ca-B12Ca.dat

#CAGE_B26Ca-B12Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGE_B26Ca-B12Ca.dat

#CAGE_B26Ca-B12Ca (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGElc_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGElc_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGElc_B26Ca-B12Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B26Ca-B12Ca >> distavg_CAGElc_B26Ca-B12Ca.dat

#wat_B28Ca-B8Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_wat_B28Ca-B8Ca.dat

#CAGE_B28Ca-B8Ca
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGE_B28Ca-B8Ca.dat

#CAGE_B28Ca-B8Ca (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGElc_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGElc_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGElc_B28Ca-B8Ca.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_B28Ca-B8Ca >> distavg_CAGElc_B28Ca-B8Ca.dat


#wat_A19O-B25H
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_wat_A19O-B25H.dat

#CAGE_A19O-B25H
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGE_A19O-B25H.dat

#CAGE_A19O-B25H (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGElc_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGElc_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGElc_A19O-B25H.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A19O-B25H >> distavg_CAGElc_A19O-B25H.dat


#wat_A21neg-B22pos
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_wat_A21neg-B22pos.dat

#CAGE_A21neg-B22pos
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGE_A21neg-B22pos.dat

#CAGE_A21neg-B22pos
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGElc_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGElc_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGElc_A21neg-B22pos.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/dist_A21neg-B22pos >> distavg_CAGElc_A21neg-B22pos.dat


gnuplot -persist << EOF
	
#B26Ca-B12Ca
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
	set key t l
        #set yrange [0:0.9]
        set title 'B26(Ca)-B12(Ca)' 
	set xrange [252:351]
	temperature = "253 294 310 350"
	set bars 4
plot "distavg_wat_B26Ca-B12Ca.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"distavg_CAGE_B26Ca-B12Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"distavg_CAGElc_B26Ca-B12Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle

#B28Ca-B8Ca
        set term x11 1
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
        set key t l
        #set yrange [0:0.9]
        set title 'B28(Ca)-B8(Ca)' 
        set xrange [252:351]
        temperature = "253 294 310 350"
	set bars 4
plot "distavg_wat_B28Ca-B8Ca.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"distavg_CAGE_B28Ca-B8Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"distavg_CAGElc_B28Ca-B8Ca.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle

#A19O-B25H
        set term x11 2
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
        set key t l
        #set yrange [0:0.9]
        set title 'A19(O)-B25(H)' 
        set xrange [252:351]
        temperature = "253 294 310 350"
	set bars 4
plot "distavg_wat_A19O-B25H.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"distavg_CAGE_A19O-B25H.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"distavg_CAGElc_A19O-B25H.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle

#A21neg-B22pos
        set term x11 3
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
        set key t l
        #set yrange [0:0.9]
        set title 'A21(negative terminal Os)-B22(postive side chain Ns)' 
        set xrange [252:351]
        temperature = "253 294 310 350"
	set bars 4
plot "distavg_wat_A21neg-B22pos.dat"   using (word(temperature,int(column(0))+1)+0.0):1  with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"distavg_CAGE_A21neg-B22pos.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"distavg_CAGElc_A21neg-B22pos.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle
	pause -1

EOF

rm distavg_*_B26Ca-B12Ca.dat
rm distavg_*_B28Ca-B8Ca.dat
rm distavg_*_A19O-B25H.dat
rm distavg_*_A21neg-B22pos.dat

