#!/bin/bash
set -e 

#6th column is 3-10

cat /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> watss_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> cagess_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> aagess_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> etss_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> ecss_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> ktss_alltemps.dat

cat /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/*K/converged_analysis/avg_all_B1-19.dat >> kcss_alltemps.dat



gnuplot -persist << EOF
	
#Alpha
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Alpha-Helicity'  
	set key b r
        #set yrange [0:0.9]
        set title 'Alpha Helicity of B1-19 in Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350"	
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "CAGE",\
"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "mCAGE",\
"etss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "EMIM_TFN",\
"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "EMIM_Cl",\
"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2 title "K_TFN",\
"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):2 with linespoints ps 2  title "K_Cl" 


#3-10 helicity
        set term x11 1  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of 3-10 Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title '3-10 Helicity of B1-19 in Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "CAGE",\
"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "mCAGE",\
"etss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "EMIM_TFN",\
"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "EMIM_Cl",\
"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2 title "K_TFN",\
"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):6 with linespoints ps 2  title "K_Cl" 


#Total helicity
        set term x11 2  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Fraction of Total Helicity'  
        set key b r
        #set yrange [0:0.9]
        set title 'Total Helicity of B1-19 in Monomer' 
        set xrange [252:351]
        #set xtics ("253" 0, "294" 1, "310" 2, "350" 3)
        temperature = "253 294 310 350" 
plot "watss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "Water",\
"cagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "CAGE",\
"aagess_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "mCAGE",\
"etss_alltemps.dat"  using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "EMIM_TFN",\
"ecss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "EMIM_Cl",\
"ktss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2 title "K_TFN",\
"kcss_alltemps.dat"   using (word(temperature,int(column(0))+1)+0.0):(column(2)+column(6)) with linespoints ps 2  title "K_Cl" 

	pause -1

EOF

rm *ss_alltemps.dat

#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

