#!/bin/bash
set -e 
#/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/*K/converged_analysis

gnuplot -persist << EOF
	
#Alpha
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
	set key b r
        set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Ionic Liquids at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "Water",\
"/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "CAGE",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "mCAGE",\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "EMIM_TFN",\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "EMIM_Cl",\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "K_TFN",\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "K_Cl"

set term x11 10  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M CAGE at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "CAGE"

set term x11 11  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Water at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "Water"

set term x11 13  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M mCAGE at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "mCAGE"

set term x11 14 
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Ionic Liquids at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "EMIM_TFN"

set term x11 15 
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Ionic Liquids at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "EMIM_Cl"


set term x11 16 
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Ionic Liquids at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "K_TFN"

set term x11 17  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Alpha-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
        set title 'Alpha Helicity of Entire Monomer Over Time in 1M Ionic Liquids at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:2 every 1000 w l title "K_Cl"

#Total Helicity
        set term x11 2  
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Time (Frames)'
        set ylabel 'Fraction of Total-Helicity'  
        set key b r
        #set yrange [0:0.9]
	set yrange [0:1]
	set title 'Total Helicity of Entire Monomer Over Time in 1M Ionic Liquid at Room Temperature' 
plot "/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "Water",\
"/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "CAGE",\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "mCAGE",\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "EMIM_TFN",\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "EMIM_Cl",\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "K_TFN",\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/1M/simulation/4-prod/294K/converged_analysis/all.dat" using 1:(column(2)+column(6)) every 1000 w l title "K_Cl"

	pause -1

EOF

