#!/bin/bash
set -e 

#/scratch/ksg225/projects/insulin/insAB/monomer_*/*M/simulation/4-prod/*K/converged_analysis/sre_analysis/rdf/rdf_ions_SRE*
#/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA


#wat
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_wat
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_wat
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_wat
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_wat

#CAGEhc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGEhc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGEhc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGEhc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGEhc

#CAGElc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGElc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGElc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGElc
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rdf/rdf_backbonetoelse >> backbonetoelse_rdfmax_CAGElc


gnuplot -persist << EOF

	set term x11 1
	set title 'RDFmax of Monomer Backbone to Everything Else'   
      	set xlabel 'Temperature (K)'
        set ylabel 'RDFmax'  
        set key t r
        temperature = "253 294 310 350"
	plot\
"backbonetoelse_rdfmax_wat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In Water" linestyle 2,\
"backbonetoelse_rdfmax_CAGElc"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In CAGE (LC)" linestyle 3,\
"backbonetoelse_rdfmax_CAGEhc"   using  (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In CAGE (HC)" linestyle 4




	pause -1

EOF

#rm backbonetoelse_rdfmax_*
                               


