#!/bin/bash
set -e 

#using 1M (high) conc for ILs
#used 500ns for wat and 500ns for IL

#wat_rog
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_wat.dat 
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_wat.dat

#CAGE_rog (HC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGE.dat

#CAGE_rog (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51 >> rmsdavg_CAGElc.dat


#wat_rog_backbone
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_wat_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_wat_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_wat_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_wat_backbone.dat

#CAGE_rog_backbone (HC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGE_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGE_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGE_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGE_backbone.dat

#CAGE_rog_backbone (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGElc_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGElc_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGElc_backbone.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rmsd/rmsd_1-51_backbone >> rmsdavg_CAGElc_backbone.dat


gnuplot -persist << EOF
	
#rog
	set term x11 0	
        set multiplot layout 2,1  rowsfirst
        set tmargin 2
        set bmargin 5 	

        set xlabel 'Temperature (K)'
        set ylabel 'RMSD (A)'  
	set key t l
        #set yrange [0:0.9]
        set title 'RMSD of Monomer (all atoms)' 
	set xrange [252:351]
	temperature = "253 294 310 350"
	set bars 4
plot "rmsdavg_wat.dat" using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"rmsdavg_CAGE.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"rmsdavg_CAGElc.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle

        set xlabel 'Temperature (K)'
        set ylabel 'RMSD (A)'  
        set key t l
        #set yrange [0:0.9]
        set title 'RMSD of Monomer (backbone)' 
        set xrange [252:351]
        temperature = "253 294 310 350"
        set bars 4
plot "rmsdavg_wat_backbone.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"rmsdavg_CAGE_backbone.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"rmsdavg_CAGElc_backbone.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle

	pause -1

EOF

rm rmsdavg_*.dat

