#!/bin/bash
set -e 

#using 1M (high) conc for ILs
#used 500ns for wat and 500ns for IL

#wat_rog
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_wat.dat 
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_wat.dat

#CAGE_rog (HC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGE.dat

#CAGE_rog (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/chainCOMdist/dist_chainCOM >> chainCOMavg_CAGElc.dat


gnuplot -persist << EOF
	
#rog
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
	set key t l
        #set yrange [0:0.9]
        set title 'Distance between COM of chains' 
	set xrange [252:351]
	temperature = "253 294 310 350"
	set bars 4
plot "chainCOMavg_wat.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"chainCOMavg_CAGE.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"chainCOMavg_CAGElc.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "In CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle
	pause -1

EOF

rm chainCOMavg_*.dat

