#!/bin/bash
set -e 



gnuplot -persist << EOF
	
#ACAGE
	set terminal postscript eps enhanced color font "/usr/share/fonts/gnu-free/FreeSans.ttf, 28" solid size 10,7 linewidth 3 
	set output 'CAGE_AAGE_sre_rdf_comparing_temps.eps'
	set multiplot layout 2,2 rows
	set tmargin 0.5
        set bmargin 4
        set lmargin 8
        set rmargin 2	
	#set border lw 2	

	#set xlabel 'Distance ({\305})' 
	set ylabel 'RDF (SREA-CAGE)' 	
	set yrange [0:9]
	set xrange [0:35] 
	set notitle
	set nokey
	plot \
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "black" title "350 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "red" title "310 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "orange" title "294 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "cyan" title "253 K"

#BCAGE
        #set xlabel 'Distance ({\305})' 
        set ylabel 'RDF (SREB-CAGE)'
	set xrange [0:35]         
        set yrange [0:9]
        set notitle 
        set nokey
	plot \
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "black" title "350 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "red" title "310 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "orange" title "294 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "cyan" title "253 K"


#AmCAGE
        set xlabel 'Distance ({\305})' 
        set ylabel 'RDF (SREA-mCAGE)'
	set xrange [0:35]         
        set yrange [0:9]
        set notitle 
        set nokey
	plot \
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "black" title "350 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "red" title "310 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "orange" title "294 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w lines lw 2 linecolor rgb "cyan" title "253 K"


#BmCAGE
        set xlabel 'Distance ({\305})' 
        set ylabel 'RDF (SREB-mCAGE)'
	set xrange [0:35]         
        set yrange [0:9]
        set notitle
        set nokey  
	plot \
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "black" title "350 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "red" title "310 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "orange" title "294 K",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w lines lw 2 linecolor rgb "cyan" title "253 K"

pause -1

EOF

#gv CAGE_AAGE_sre_rdf_comparing_temps.eps
epstopdf CAGE_AAGE_sre_rdf_comparing_temps.eps


