#!/bin/bash
set -e 



gnuplot -persist << EOF

#ACAGE
	set term x11 1
	set font '{/Times-New-Roman=18 a}' 
	set xlabel 'Distance (A)' 
	set ylabel 'RDF' 	
	set yrange [0:9]
	set xrange [0:20] 
	set title 'RDFs of SREA Center of Mass to CAGE'
	set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"

#BCAGE
        set term x11 2
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
	set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to CAGE'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"


#AmCAGE
        set term x11 3
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
	set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREA Center of Mass to mCAGE'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"


#BmCAGE
        set term x11 4
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
	set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to mCAGE'
        set key t r  
	set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan" ,\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"



#A_EMIM_TFN
        set term x11 5
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREA Center of Mass to EMIM_TFN'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"


#B_EMIM_TFN
        set term x11 6
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to EMIM_TFN'
        set key t r  
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan" ,\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"



#A_EMIM_Cl
        set term x11 7
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREA Center of Mass to EMIM_Cl'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"


#B_EMIM_Cl
        set term x11 8
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to EMIM_Cl'
        set key t r  
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan" ,\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"



#A_K_TFN
        set term x11 9
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREA Center of Mass to K_TFN'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"


#B_K_TFN
        set term x11 10
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to K_TFN'
        set key t r  
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan" ,\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"



#A_K_Cl
        set term x11 11
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREA Center of Mass to K_Cl'
        set key t r
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "253 K" linecolor rgb "cyan",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA' w l title "350 K" linecolor rgb "black"


#B_K_Cl
        set term x11 12
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Distance (A)' 
        set ylabel 'RDF'
        set xrange [0:20]         
        set yrange [0:9]
        set title 'RDFs of SREB Center of Mass to K_Cl'
        set key t r  
        set key spacing 1.5
plot '/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "253 K" linecolor rgb "cyan" ,\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "294 K" linecolor rgb "orange",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "310 K" linecolor rgb "red",\
'/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB' w l title "350 K" linecolor rgb "black"


pause -1

EOF


