#!/bin/bash
set -e 



gnuplot -persist << EOF
#A

        set term x11 0
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'RDF' at screen 0.45,0.005
        set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
        set style data histograms
        set key off
	set yrange [0:0.8]
        set xrange [0:9]
        set xlabel "RDF"
        set label 3 'Alpha Helicity vs RDF Max of SRE A' at screen 0.23,0.98
 
        set title "253K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreA_253" using  4:3 via a,b
	plot "alpha_rdfmax_mon_sreA_253" using  4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)
        
	set title "294K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreA_294" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreA_294" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x) 

        set title "310K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreA_310" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreA_310" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)

        set title "350K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreA_350" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreA_350" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)



        
	unset multiplot

#B

        set term x11 1
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'RDF' at screen 0.45,0.005
        set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
        set style data histograms
        set key off
        set yrange [0:0.8]
        set xrange [0:9]
        set xlabel "RDF"
        set label 3 'Alpha Helicity vs RDF Max of SRE B' at screen 0.23,0.98
        
        set title "253K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreB_253" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreB_253" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x) 

        set title "294K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreB_294" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreB_294" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)

        set title "310K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreB_310" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreB_310" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)

        set title "350K"
        f(x) = a*x +b
        fit f(x) "alpha_rdfmax_mon_sreB_350" using 4:3 via a,b
        plot "alpha_rdfmax_mon_sreB_350" using 4:3:2 with labels offset char 1,1 point pt 7 lt rgb "blue", f(x)



        
        unset multiplot



EOF
