#!/bin/bash
set -e 

#using 1M (high) conc for ILs
#used 500ns for wat and 500ns for IL

#wat_rog
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.dat 
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_wat.dat

#CAGE_rog (HC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/1M/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGE.dat

#CAGE_rog (LC)
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGElc.dat
./../../../analysis_scripts/avg_sterror 2 /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/analysis_1us/rog_and_dist_1us/prod.mono.radgyr.conv.1us.out >> rogavg_CAGElc.dat


gnuplot -persist << EOF
	
#rog
	set term x11 0	
        set font '{/Times-New-Roman=18 a}' 
        set xlabel 'Temperature (K)'
        set ylabel 'Distance (A)'  
	set key t l
        #set yrange [0:0.9]
        set title 'Radius of Gyration of Monomer' 
	set xrange [252:351]
	temperature = "253 294 310 350"
	set bars 4
plot "rogavg_wat.dat"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "Water" linestyle 1, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 1 notitle,\
"rogavg_CAGE.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (HC)" linestyle 2, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 2 notitle,\
"rogavg_CAGElc.dat"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE (LC)" linestyle 3, "" using (word(temperature,int(column(0))+1)+0.0):1:3 with yerrorbars linetype 3 notitle
	pause -1

EOF

rm rogavg_*.dat

