#!/bin/bash
set -e 

#6th column is 3-10

gnuplot -persist << EOF
	set term x11 0
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'Solvent' at screen 0.45,0.005
        set label 2 'Fraction of 3-10 Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.5
	set style data histogram
	set style fill solid
	set key off
        #set yrange [0:0.9]
	set xtic rotate by -30
        set label 3 '3-10 Helicity of Entire Monomer' at screen 0.23,0.98
	set xrange [0:7.5]

	
        set title "253K"
	set xtics ("Water" 1, "CAGE" 2, "mCAGE" 3, "EMIM_TFN" 4, "EMIM_Cl" 5, "K_TFN" 6, "K_Cl" 7)
	plot "/scratch/ksg225/projects/insulin/insAB/monomer/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6,\
"/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_AAGE/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 ,\
"/scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/simulation/4-prod/253K/converged_analysis/avg_all.dat" using 6 



	#set title "294K"
        #plot "alpha_mon_all_294.dat" using 1:3:4:xtic(2) with boxerrorbars
	
	#set title "310K"
        #plot "alpha_mon_all_310.dat" using 1:3:4:xtic(2) with boxerrorbars

	#set title "350K"
        #plot "alpha_mon_all_350.dat" using 1:3:4:xtic(2) with boxerrorbars
	
	unset multiplot


	pause -1

EOF


#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

