#!/bin/bash
set -e 

cp monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253CAGE_A
cp monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253CAGE_B
cp monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253AAGE_A
cp monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253AAGE_B
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253E_T_A
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253E_T_B
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253E_A
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253E_B
cp monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253T_A
cp monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253T_B

cp monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294CAGE_A
cp monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294CAGE_B
cp monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294AAGE_A
cp monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294AAGE_B
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294E_T_A
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294E_T_B
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294E_A
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294E_B
cp monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294T_A
cp monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294T_B

cp monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310CAGE_A
cp monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310CAGE_B
cp monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310AAGE_A
cp monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310AAGE_B
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310E_T_A
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310E_T_B
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310E_A
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310E_B
cp monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310T_A
cp monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310T_B

cp monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350CAGE_A
cp monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350CAGE_B
cp monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350AAGE_A
cp monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350AAGE_B
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350E_T_A
cp monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350E_T_B
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350E_A 
cp monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350E_B
cp monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350T_A
cp monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350T_B

cp monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 253K_C_A	
cp monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 253K_C_B
cp monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 294K_C_A
cp monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 294K_C_B
cp monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 310K_C_A
cp monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 310K_C_B
cp monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA 350K_C_A
cp monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB 350K_C_B


gnuplot -persist << EOF

#A
	set term x11 0
	set multiplot layout 2,2  rowsfirst
	set title '{/Times-New-Roman=18 a}' 
	set label 1 'Distance (A)' at screen 0.45,0.005
	set label 2 'RDF' at screen 0.01,0.4 rotate by 90	
	
	set yrange [0:9]

	set label 3 'RDF of SRE Center of Mass on Chain A to Ions' at screen 0.23,0.98
	set title "253K"
	set key t r
	plot '253CAGE_A' w l title "CAGE",\
	'253AAGE_A' w l title "mCAGE (A14)",\
	'253E_T_A' w l title "EMIM_TFN",\
	'253E_A' w l title "EMIM_Cl",\
	'253K_C_A' w l title "K_Cl" ,\
	'253T_A' w l title "K_TFN"


	set title "294K"
        set key t r
        plot '294CAGE_A' w l title "CAGE",\
        '294AAGE_A' w l title "mCAGE (A14)",\
        '294E_T_A' w l title "EMIM_TFN",\
        '294E_A' w l title "EMIM_Cl",\
	'294K_C_A' w l title "K_Cl" ,\
        '294T_A' w l title "K_TFN"	

        set title "310K"
        set key t r
        plot '310CAGE_A' w l title "CAGE",\
        '310AAGE_A' w l title "mCAGE (A14)",\
        '310E_T_A' w l title "EMIM_TFN",\
        '310E_A' w l title "EMIM_Cl",\
	'310K_C_A' w l title "K_Cl" ,\
        '310T_A' w l title "K_TFN" 


        set title "350K"
        set key t r
        plot '350CAGE_A' w l title "CAGE",\
        '350AAGE_A' w l title "mCAGE (A14)",\
        '350E_T_A' w l title "EMIM_TFN",\
        '350E_A' w l title "EMIM_Cl",\
        '350K_C_A' w l title "K_Cl" ,\
        '350T_A' w l title "K_TFN" 

#B
	unset multiplot
        set term x11 1
        set multiplot layout 2,2  rowsfirst
        set title '{/Times-New-Roman=18 a}' 
        set label 1 'Distance (A)' at screen 0.45,0.005
        set label 2 'RDF' at screen 0.01,0.4 rotate by 90       
        
	set yrange [0:9]

        set label 3 'RDF of SRE Center of Mass on Chain B to Ions' at screen 0.23,0.98
        set title "253K"
        set key t r
        plot '253CAGE_B' w l title "CAGE",\
        '253AAGE_B' w l title "mCAGE (A14)",\
        '253E_T_B' w l title "EMIM_TFN",\
        '253E_B' w l title "EMIM_Cl",\
        '253K_C_B' w l title "K_Cl" ,\
        '253T_B' w l title "K_TFN"


        set title "294K"
        set key t r
        plot '294CAGE_B' w l title "CAGE",\
        '294AAGE_B' w l title "mCAGE (A14)",\
        '294E_T_B' w l title "EMIM_TFN",\
        '294E_B' w l title "EMIM_Cl",\
        '294K_C_B' w l title "K_Cl" ,\
        '294T_B' w l title "K_TFN"        

        set title "310K"
        set key t r
        plot '310CAGE_B' w l title "CAGE",\
        '310AAGE_B' w l title "mCAGE (A14)",\
        '310E_T_B' w l title "EMIM_TFN",\
        '310E_B' w l title "EMIM_Cl",\
        '310K_C_B' w l title "K_Cl" ,\
        '310T_B' w l title "K_TFN" 


        set title "350K"
        set key t r
        plot '350CAGE_B' w l title "CAGE",\
        '350AAGE_B' w l title "mCAGE (A14)",\
        '350E_T_B' w l title "EMIM_TFN",\
        '350E_B' w l title "EMIM_Cl",\
        '350K_C_B' w l title "K_Cl" ,\
        '350T_B' w l title "K_TFN" 



pause -1

EOF


rm 253AAGE_A         
rm 253T_B            
rm 294T_A            
rm 310E_T_B          
rm 350E_T_A    
rm 253AAGE_B         
rm 294AAGE_A         
rm 294T_B            
rm 310T_A            
rm 350E_T_B          
rm 253CAGE_A         
rm 294AAGE_B         
rm 310AAGE_A         
rm 310T_B            
rm 350T_A            
rm 253CAGE_B         
rm 294CAGE_A         
rm 310AAGE_B         
rm 350AAGE_A         
rm 350T_B            
rm 253E_A            
rm 294CAGE_B         
rm 310CAGE_A         
rm 350AAGE_B               
rm 253E_B            
rm 294E_A            
rm 310CAGE_B         
rm 350CAGE_A             
rm 253E_T_A          
rm 294E_B            
rm 310E_A            
rm 350CAGE_B              
rm 253E_T_B          
rm 294E_T_A          
rm 310E_B            
rm 350E_A             
rm 253T_A            
rm 294E_T_B          
rm 310E_T_A         
rm 350E_B
rm 253K_C_A
rm 253K_C_B
rm 294K_C_A
rm 294K_C_B
rm 310K_C_A
rm 310K_C_B
rm 350K_C_A
rm 350K_C_B
