#!/bin/bash
set -e 

#/scratch/ksg225/projects/insulin/insAB/monomer_*/*M/simulation/4-prod/*K/converged_analysis/sre_analysis/rdf/rdf_ions_SRE*
#/scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA


#CAGEA
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_CAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_CAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_CAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_CAGE_A

#AAGE-A ie mCAGE-A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_AAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_AAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_AAGE_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_AAGE_A

#etA
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_et_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_et_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_et_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_et_A

#ecA
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_ec_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_ec_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_ec_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_ec_A

#ktA
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kt_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kt_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kt_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kt_A

#kcA
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kc_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kc_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kc_A
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREA >> srerdfmaxdist_sremax_kc_A



#CAGEB
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_CAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_CAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_CAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_CAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_CAGE_B

#AAGE-B ie mCAGE-B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_AAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_AAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_AAGE_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_AAGE/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_AAGE_B

#etB
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_et_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_et_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_et_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_et_B

#ecB
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_ec_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_ec_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_ec_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_EMIM_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_ec_B

#ktB
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kt_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kt_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kt_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_TFN/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kt_B

#kcB
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/253K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kc_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/294K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kc_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/310K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kc_B
awk -v max=0 'NR > 1 {if($2>max){first=$1; second=$2; max=$2}}END{print first, second} ' /scratch/ksg225/projects/insulin/insAB/monomer_K_Cl/0.0XM/simulation/4-prod/350K/converged_analysis/sre_analysis/rdf/rdf_ions_SREB >> srerdfmaxdist_sremax_kc_B



gnuplot -persist << EOF

#getting rid of first buggy window
	set term x11 1
	set title 'Likely Distance of Ionic Liquids from SRE-A vs Temperature'   
      	set xlabel 'Temperature (K)'
        set ylabel 'Likely Distance of Ionic Liquids from SRE-A (A)'  
        set key t r
        temperature = "253 294 310 350"
	plot\
"srerdfmaxdist_sremax_CAGE_A"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE" linestyle 2,\
"srerdfmaxdist_sremax_AAGE_A"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "mCAGE" linestyle 3,\
"srerdfmaxdist_sremax_et_A"   using  (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][TFN]" linestyle 4,\
"srerdfmaxdist_sremax_ec_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][Cl]" linestyle 5,\
"srerdfmaxdist_sremax_kt_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[K][TFN]" linestyle 6,\
"srerdfmaxdist_sremax_kc_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints  title "[K][Cl]" linestyle 7



#B
        set term x11 2
        set title 'Likely Distance of Ionic Liquids from SRE-B vs Temperature'   
        set xlabel 'Temperature (K)'
        set ylabel 'Likely Distance of Ionic Liquids from SRE-B (A)'  
        set key t r
	set xrange [253:350]
        temperature = "253 294 310 350"
        plot\
"srerdfmaxdist_sremax_CAGE_B"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE" linestyle 1,\
"srerdfmaxdist_sremax_AAGE_B"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "mCAGE" linestyle 3,\
"srerdfmaxdist_sremax_et_B"   using  (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][TFN]" linestyle 4,\
"srerdfmaxdist_sremax_ec_B"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][Cl]" linestyle 5,\
"srerdfmaxdist_sremax_kt_B"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[K][TFN]" linestyle 6,\
"srerdfmaxdist_sremax_kc_B"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints  title "[K][Cl]" linestyle 7

#A
        set term x11 3
        set title 'Likely Distance of Ionic Liquids from SRE-A vs Temperature'   
        set xlabel 'Temperature (K)'
        set ylabel 'Likely Distance of Ionic Liquids from SRE-A (A)'  
        set key t r
	set xrange [253:350]
        temperature = "253 294 310 350"
        plot\
"srerdfmaxdist_sremax_CAGE_A"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "CAGE" linestyle 1,\
"srerdfmaxdist_sremax_AAGE_A"  using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "mCAGE" linestyle 3,\
"srerdfmaxdist_sremax_et_A"   using  (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][TFN]" linestyle 4,\
"srerdfmaxdist_sremax_ec_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[EMIM][Cl]" linestyle 5,\
"srerdfmaxdist_sremax_kt_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints title "[K][TFN]" linestyle 6,\
"srerdfmaxdist_sremax_kc_A"   using (word(temperature,int(column(0))+1)+0.0):1 with linespoints  title "[K][Cl]" linestyle 7

	pause -1

EOF

rm srerdfmaxdist_sremax_*
                               


