#!/bin/bash
set -e 



gnuplot -persist << EOF
	
        set terminal postscript eps enhanced color font "/usr/share/fonts/gnu-free/FreeSans.ttf, 32" solid size 12,10 linewidth 2
        set output 'FE_350K_1M_100ns.eps'
	set border lw 2
	set key spacing 1.1
        set title "Potential of Mean Force of Dimerization at 350 K"    
	
	set xlabel 'Distance Between Center of Mass of Monomers (nm)'
        set ylabel 'Free Energy (kcal/mol)'  
	set key b r
        #set yrange [0:1]
	set xrange [1.65:3.65]

	plot \
"/scratch/ksg225/projects/insulin/3u4n/dimer/simulation/4-prod/350K/smd/US/analysis_100ns/free_energy.out"  using 1:2 w l lw 6 linecolor rgb "#0072B2" title "In Water",\
"/scratch/ksg225/projects/insulin/3u4n/dimer_CAGE/1M/simulation/4-prod/350K/smd/US/analysis_100ns/free_energy.out"  using 1:2 w l lw 6 linecolor rgb "#009E73" title "In CAGE",\
"/scratch/ksg225/projects/insulin/3u4n/dimer_AAGE/1M/simulation/4-prod/350K/smd/US/analysis_100ns/free_energy.out"  using 1:2 w l lw 6 linecolor rgb "#D55E00" title "In mCAGE"
	pause -1

EOF


#gv plot_ssalpha_wat.CAGE.AAGE_over_temp_1M_pops_handled.eps
#epstopdf FE_350K_1M_100ns.eps


