#!/bin/bash
set -e 



gnuplot -persist << EOF
	set term x11 0
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'Solvent' at screen 0.45,0.005
        set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
	set style data histogram
	set style fill solid
	set key off
        set yrange [0:0.7]
	set xtic rotate by -30
        set label 3 'Alpha Helicity of Entire Dimer' at screen 0.23,0.98
	set xrange [0:7.5]

        set title "253K"
	plot "alpha_di_all_253.dat" using 1:3:4:xtic(2) with boxerrorbars

	set title "294K"
        plot "alpha_di_all_294.dat" using 1:3:4:xtic(2) with boxerrorbars
	
	set title "310K"
        plot "alpha_di_all_310.dat" using 1:3:4:xtic(2) with boxerrorbars

	set title "350K"
        plot "alpha_di_all_350.dat" using 1:3:4:xtic(2) with boxerrorbars
	
	unset multiplot

#B1-19

        set term x11 1
        set multiplot layout 2,2  rowsfirst
        set font '{/Times-New-Roman=18 a}' 
        set label 1 'Solvent' at screen 0.45,0.005
        set label 2 'Fraction of Alpha Helicity' at screen 0.01,0.4 rotate by 90       
        set boxwidth 0.3
        set style data histogram
        set style fill solid
        set key off
        set yrange [0:0.7]
        set xtic rotate by -30
        set label 3 'Alpha Helicity of B1-19 in Dimer' at screen 0.23,0.98
        set xrange [0:7.5]

        set title "253K"
        plot "alpha_di_B1-19_253.dat" using 1:3:4:xtic(2) with boxerrorbars

        set title "294K"
        plot "alpha_di_B1-19_294.dat" using 1:3:4:xtic(2) with boxerrorbars
        
        set title "310K"
        plot "alpha_di_B1-19_310.dat" using 1:3:4:xtic(2) with boxerrorbars

        set title "350K"
        plot "alpha_di_B1-19_350.dat" using 1:3:4:xtic(2) with boxerrorbars



	pause -1

EOF


#alpha_hex_all_253.dat  alpha_hex_B1-19_253.dat

