#!/bin/bash
set -e 

cp dimer/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_w.dat
cp dimer_CAGE/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_c.dat
cp dimer_AAGE/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_a.dat
cp dimer_EMIM_TFN/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_et.dat
cp dimer_EMIM_Cl/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_ec.dat
cp dimer_K_TFN/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_kt.dat
cp dimer_K_Cl/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_kc.dat

gnuplot -persist << EOF
	set title '{/Times-New-Roman=18 a}' 
	set xlabel "Subunit Distance (A)"
	set ylabel "Free Energy (kcal/mol)"
	set key bottom right
	set title "Dimer ABMD in Variable Solvent at 253K"
	
	plot 'FE_w.dat' w l title "Water",\
	'FE_c.dat' w l title "CAGE",\
	'FE_a.dat' w l title "mCAGE (A14)",\
	'FE_et.dat' w l title "EMIM_TFN",\
	'FE_ec.dat' w l title "EMIM_Cl",\
	'FE_kt.dat' w l title "K_TFN",\
	'FE_kc.dat' w l title "K_Cl"
	pause -1

EOF


rm FE*.dat





