#!/bin/bash
set -e 

cp dimer/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253w.dat
cp dimer_CAGE/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253c.dat
cp dimer_AAGE/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253a.dat
cp dimer_EMIM_TFN/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253et.dat
cp dimer_EMIM_Cl/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253ec.dat
cp dimer_K_TFN/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253kt.dat
cp dimer_K_Cl/0.0XM/simulation/4-prod/253K/abmd/2.abmd/FE.dat FE_253kc.dat
cp dimer/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294w.dat
cp dimer_CAGE/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294c.dat
cp dimer_AAGE/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294a.dat
cp dimer_EMIM_TFN/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294et.dat
cp dimer_EMIM_Cl/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294ec.dat
cp dimer_K_TFN/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294kt.dat
cp dimer_K_Cl/0.0XM/simulation/4-prod/294K/abmd/2.abmd/FE.dat FE_294kc.dat
cp dimer/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310w.dat
cp dimer_CAGE/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310c.dat
cp dimer_AAGE/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310a.dat
cp dimer_EMIM_TFN/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310et.dat
cp dimer_EMIM_Cl/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310ec.dat
cp dimer_K_TFN/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310kt.dat
cp dimer_K_Cl/0.0XM/simulation/4-prod/310K/abmd/2.abmd/FE.dat FE_310kc.dat
cp dimer/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350w.dat
cp dimer_CAGE/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350c.dat
cp dimer_AAGE/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350a.dat
cp dimer_EMIM_TFN/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350et.dat
cp dimer_EMIM_Cl/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350ec.dat
cp dimer_K_TFN/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350kt.dat
cp dimer_K_Cl/0.0XM/simulation/4-prod/350K/abmd/2.abmd/FE.dat FE_350kc.dat

gnuplot -persist << EOF
	set multiplot layout 2,2 rowsfirst
	set label 1 'Subunit Distance (A)' at screen 0.46,0.005
        set label 2 'Free Energy (kcal/mol)' at screen 0.01,0.4 rotate by 90  
	set tmargin 2
	set bmargin 2
	set lmargin 5
	set rmargin 2
	set title '{/Times-New-Roman=18 a}' 
	#set xlabel "Subunit Distance (A)"
	#set ylabel "Free Energy (kcal/mol)"
	set key off
	set yrange [-150:0]

	#set label 3 'Dimer ABMD in Variable Solvent at Four Relevant Temperatures' at screen 0.23,0.98
	set title "253K" font "0{,20}"
	set key spacing .7
	set key off
	plot 'FE_253w.dat' w l title "Water",\
	'FE_253c.dat' w l title "CAGE",\
	'FE_253a.dat' w l title "mCAGE",\
	'FE_253et.dat' w l title "[EMIM][TFN]",\
	'FE_253ec.dat' w l title "[EMIM][Cl]",\
	'FE_253kt.dat' w l title "[K][TFN]",\
	'FE_253kc.dat' w l title "[K][Cl]"

	set title '{/Times-New-Roman=18 a}' 
        #set xlabel "Subunit Distance (A)"
        #set ylabel "Free Energy (kcal/mol)"
	set key spacing .7
	set key off
        set title "294K"        
        plot 'FE_294w.dat' w l title "Water",\
        'FE_294c.dat' w l title "CAGE",\
        'FE_294a.dat' w l title "mCAGE",\
        'FE_294et.dat' w l title "[EMIM][TFN]",\
        'FE_294ec.dat' w l title "[EMIM][Cl]",\
        'FE_294kt.dat' w l title "[K][TFN]",\
        'FE_294kc.dat' w l title "[K][Cl]"

         set title '{/Times-New-Roman=18 a}' 
        #set xlabel "Subunit Distance (A)"
        #set ylabel "Free Energy (kcal/mol)"
	set key spacing .7
	set key off
        set title "310K"        
        plot 'FE_310w.dat' w l title "Water",\
        'FE_310c.dat' w l title "CAGE",\
        'FE_310a.dat' w l title "mCAGE",\
        'FE_310et.dat' w l title "[EMIM][TFN]",\
        'FE_310ec.dat' w l title "[EMIM][Cl]",\
        'FE_310kt.dat' w l title "[K][TFN]",\
        'FE_310kc.dat' w l title "[K][Cl]"

  set title '{/Times-New-Roman=18 a}' 
        #set xlabel "Subunit Distance (A)"
        #set ylabel "Free Energy (kcal/mol)"
	set key spacing .7
	set key off
        set title "350K"        
        plot 'FE_350w.dat' w l title "Water",\
        'FE_350c.dat' w l title "CAGE",\
        'FE_350a.dat' w l title "mCAGE",\
        'FE_350et.dat' w l title "[EMIM][TFN]",\
        'FE_350ec.dat' w l title "[EMIM][Cl]",\
        'FE_350kt.dat' w l title "[K][TFN]",\
        'FE_350kc.dat' w l title "[K][Cl]"

	pause -1

EOF


rm FE*.dat





