#!/bin/bash
set -e 



gnuplot -persist << EOF
	set multiplot layout 2,2 rowsfirst 
	set xlabel 'Distance (A)' 
        set ylabel 'Work at 253 K'    
        set notitle
        set key t r
	plot \
'/scratch/ksg225/projects/insulin/3u4n/dimer/simulation/4-prod/253K/smd/smd/smd.txt' u 3:5 w l title 'In Water',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_CAGE/1M/simulation/4-prod/253K/smd/smd/smd.txt' u 3:5 w l title 'In CAGE',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_AAGE/1M/simulation/4-prod/253K/smd/smd/smd.txt' u 3:5 w l title 'In mCAGE'

        set xlabel 'Distance (A)' 
        set ylabel 'Work at 294 K'    
        set notitle
        set key t r
        plot \
'/scratch/ksg225/projects/insulin/3u4n/dimer/simulation/4-prod/294K/smd/smd/smd.txt' u 3:5 w l title 'In Water',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_CAGE/1M/simulation/4-prod/294K/smd/smd/smd.txt' u 3:5 w l title 'In CAGE',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_AAGE/1M/simulation/4-prod/294K/smd/smd/smd.txt' u 3:5 w l title 'In mCAGE'

        set xlabel 'Distance (A)' 
        set ylabel 'Work at 310 K'    
        set notitle
        set key t r
        plot \
'/scratch/ksg225/projects/insulin/3u4n/dimer/simulation/4-prod/310K/smd/smd/smd.txt' u 3:5 w l title 'In Water',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_CAGE/1M/simulation/4-prod/310K/smd/smd/smd.txt' u 3:5 w l title 'In CAGE',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_AAGE/1M/simulation/4-prod/310K/smd/smd/smd.txt' u 3:5 w l title 'In mCAGE'

        set xlabel 'Distance (A)' 
        set ylabel 'Work at 350 K'    
        set notitle
        set key t r
        plot \
'/scratch/ksg225/projects/insulin/3u4n/dimer/simulation/4-prod/350K/smd/smd/smd.txt' u 3:5 w l title 'In Water',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_CAGE/1M/simulation/4-prod/350K/smd/smd/smd.txt' u 3:5 w l title 'In CAGE',\
'/scratch/ksg225/projects/insulin/3u4n/dimer_AAGE/1M/simulation/4-prod/350K/smd/smd/smd.txt' u 3:5 w l title 'In mCAGE'


	pause -1



EOF
